const swaggerAutogen = require("swagger-autogen")();

const doc = {
  info: {
    version: "1.0.0",
    title: "Task Manager API",
    description: "Task Manager API Documentation(autogenerated)",
  },
  host: "localhost:5000",
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],
};

const outputFile = "./swagger_output.json";
const endpointsFiles = ["./routers/index.js"];

swaggerAutogen(outputFile, endpointsFiles, doc);
